name: memory_game
description: Jogo da memória.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg:  ^2.0.9
  cupertino_icons: ^1.0.2
  flutter_animate: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/pngs/

  fonts:
    - family: OctoberCrow
      fonts:
        - asset: assets/font/OctoberCrow.ttf


    - family: Baloo
      fonts:
        - asset: assets/font/Baloo2-Regular.ttf
          weight: 500
